[package]
name = "token"
version = "0.1.0"
authors = ["Petar Vujović <petarvujovic98@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-contract-standards = "4.1.1"
near-sdk = "4.1.1"
near-sdk-contract-tools = "0.7.2"
